[package]
name = "bftgrid-mt"
version = "0.0.1"
edition = "2021"
authors = ["Fabio Tudone <fabtud@gmail.com>"]

[dependencies]
bftgrid-core = { path = "../bftgrid-core" }
tokio = { version = "1.35.1", features = ["macros", "rt-multi-thread", "sync", "time"] }
async-trait = "0.1.77"
