[package]
name = "bft-grid-sim"
version = "0.0.1"
edition = "2021"
authors = ["Fabio Tudone <fabtud@gmail.com>"]

[dependencies]
bft-grid-core = { path = "../bft-grid-core" }

[[bin]]
name = "bft-grid-sim"
path = "src/bin.rs"
