[package]
name = "bftgrid-sim"
version = "0.0.1"
edition = "2021"
authors = ["Fabio Tudone <fabtud@gmail.com>"]

[dependencies]
bftgrid-core = { path = "../bftgrid-core" }
async-trait = "0.1.77"
rand_chacha = "0.3.1"
dyn-clone = "1.0.16"
serde = "1.0.197"
